#!/bin/bash

VIMRC="/usr/share/vim/vimrc"
BASHRC="$HOME/.bashrc"

# Make sure only root can run the script
if [[ $EUID -ne 0 ]]
then
   echo "This script must be run as root" 1>&2
   echo 'Run with "sudo ./add-settings"'
   exit 1
fi

cat settings/vimrc >> $VIMRC && echo "Added settings to $VIMRC"
cat settings/bashrc >> $BASHRC && echo "Added settings to $BASHRC"
