

map <S-Left> :tabp<Enter>
map <S-Right> :tabn<Enter>

filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab

"set smartindent
"set autoindent

autocmd BufNewFile *.py 0put =\"#!/usr/bin/env python3\<nl>\<nl>\"|$
autocmd BufNewFile *.sh 0put =\"#!/bin/bash\<nl>\<nl>\"|$
